### PR TITLE
Test splitting tests of crates to ensure all gets tested

### LINKED ISSUE #43: Track changes of the subcrates, as av itself is mostly empty
From the discussion in #42

### PR DESCRIPTION
**Pull request by Coding-Doctors**
Coveralls may take a bit of working with to get all the coverage for, ideally this will work perfectly as it is.
Fixes #43

### CODE REVIEW

**Comment by Coding-Doctors** [comment]
I'll change it once travis is done, but the correct way to set variables that don't change is like this, just forgot about it when I first set it.
```yml
env:
    global:
        - PATH=$HOME/.cargo/bin:$PATH
        - CARGO_FEATURES_DEFAULT=["nightly"]
    matrix:
        - CRATE=bitstream
        - CRATE=codec
        - CRATE=data
        - CRATE=format
        - CRATE=av
```

**Comment by Coding-Doctors** [comment]
As I thought the coverage is run on the root only, rather than gathered from other tests.

**Comment by lu-zero** [comment]
I'm afraid that could confuse a lot coveralls.

**Comment by Coding-Doctors** [comment]
Yeah it might, I'll wait for it to get finished to really get in and change things but its worth a try raw at least.

**Comment by Coding-Doctors** [comment]
Not sure why codec is complaining about Errorkind not existing https://travis-ci.org/rust-av/rust-av/jobs/334109273#L1206

**Comment by lu-zero** [comment]
Because I forgot to update that specific test to `Failure`.

**Comment by lu-zero** [comment]
Now that part should be fine as well.

**Comment by lu-zero** [comment]
I would consolidate the current set in a single patch and push it, looks like the remaining issue is related to either kcov or the travis runner.

**Comment by Coding-Doctors** [comment]
Yeah, I agree not much more that can really be done on my end. Squashed and pushed.

**Comment by lu-zero** [comment]
I'd amend the commit message with:

```
    ci: Split travis coverage per subcrate

    Run the tests for each subcrate using a matrix.

    Coveralls should work out of box, but there are some kcov issues that
    prevent it from building correctly on the current travis runner.
```

And push on master tomorrow if you are fine with my summary.

**Comment by Coding-Doctors** [comment]
LGTM 👍

**Comment by Coding-Doctors** [comment]
Alright amended and pushed!

**Comment by lu-zero** [comment]
Great :) hopefully kcov support will be fixed by upstream.

**Comment by Coding-Doctors** [comment]
I hope so too.

**Pull request merged**
