### PR TITLE
av-data: include license file in published crates

### PR DESCRIPTION
**Pull request by decathorpe**
The `MIT` license requires that redistributed sources contain a copy of the license text. This is currently not the case for the `av-data` crate as published on crates.io (I'm packaging it for Fedora Linux as a dependency of the `dav1d` bindings and `gst-plugin-dav1d`).

This issue also applies to the other crates in this workspace, but the `av-data` crate seems to be developed on its own branch in git, so I just applied the change for this one crate for now.

It would be great if you could publish a new release (v0.4.3?) of the av-data crate after this change lands, it would make my work on packaging the dav1d GStreamer plugin easier.

### CODE REVIEW

**Review by lu-zero — CHANGES_REQUESTED** [review]
Wouldn't be enough to add a [include](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) or, even better, a workspace `license-file` entry?

**Comment by lu-zero** [comment]
I assumed the license file would be picked automatically, thank you for reporting the problem.

**Comment by decathorpe** [comment]
No, as far as I know, `include` does not work for files that are in "parent" directories. And the `license-file` setting is supposed to only be used for non-standard licenses that are not expressible with an SPDX expression:

> If a package is using a nonstandard license, then the license-file field may be specified in lieu of the license field.

https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

**Comment by lu-zero** [comment]
I hoped we couldn't have too many not really needed files around... let me experiment a little

**Comment by decathorpe** [comment]
As far as I can tell, the only way to include license file(s) in workspace members that both *works* and is compliant with cargo docs / crates.io behaviour *is* to add a symbolic link (or a copy of the file, in case you run `cargo publish` on an OS that doesn't have working symbolic links, i.e. Windows). All projects I've dealt with in the past do either the one (symlink) or the other (copy of the file), but most use symlinks.

**Comment by lu-zero** [comment]
I guess it should be fixed in Cargo itself :E

**Comment by lu-zero** [comment]
Also it is not developed in a branch...

**Comment by lu-zero** [comment]
Let me remove that misleading branch.

**Comment by lu-zero** [comment]
if you could reopen the pr against master would be great.

**Comment by lu-zero** [comment]
Or I can just cherry-pick it and bake a release :)

**Comment by decathorpe** [comment]
> I guess it should be fixed in Cargo itself :E

I agree :( But I don't think there's currently a better solution than the symlinks.

Thanks a lot for merging + the new release!

**Comment by lu-zero** [comment]
Thank you for providing a fix and explaining the problem :)

**Pull request merged**
