### PR TITLE
Update err_derive

### PR DESCRIPTION
**Pull request by xd009642**

### CODE REVIEW

**Comment by xd009642** [comment]
I should have done a PR branch for this, didn't realise I was on master :man_facepalming:

**Comment by xd009642** [comment]
I thought it was a rust fmt breakage? Given it's just formatting and the actual err_derive update I'd personally be tempted to just do a squash and merge personally. But I can reorder things though it will have to wait till tomorrow as it's quite late here

**Comment by lu-zero** [comment]
If you do would be nice otherwise I can just rebase what you have here.

**Comment by xd009642** [comment]
Yeah sure, if you don't mind waiting I'll do it when I get home around 8pm GMT

**Comment by lu-zero** [comment]
Thank you a lot :)

**Comment by xd009642** [comment]
So I deleted the rust fmt commit and added it to another PR (#99). We've seen this one passes CI with the rustfmt changes on #99 so it should be all good :+1:

**Pull request merged**
